#!/bin/sh -e

###
# Rebuild kernel module map
###
depmod -a

# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e /boot/System.map-4.4.190.x86_64.1 ]; then
		depmod -a -F /boot/System.map-4.4.190.x86_64.1 4.4.190.x86_64.1 || true
	fi
fi
# End automatically added section
# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e /boot/System.map-4.4.218.x86_64.1 ]; then
		depmod -a -F /boot/System.map-4.4.218.x86_64.1 4.4.218.x86_64.1 || true
	fi
fi
# End automatically added section


exit 0
