#!/bin/sh

cat > "$ADTTMP"/smoketest.py <<EOF
def foo():
    return 'yes'

def test_foo():
    assert foo() == 'yes'

EOF

cd "$ADTTMP"

for py in $(py3versions -i); do
    TMPDIR="$ADTTMP" $py -m pytest smoketest.py
done
