#!/bin/sh
set -efu

pys="$(pyversions -r 2>/dev/null)"

cd "$AUTOPKGTEST_TMP"

for py in $pys; do
	echo "=== $py ==="
	$py -c "import Cython; import Cython.Compiler.Code"
	${py}-dbg -c "import Cython; import Cython.Compiler.Code"
done
