#!/usr/bin/python3

import sys
import iso8601

from datetime import datetime, timezone

status = (iso8601.parse_date("2007-01-25T12:00:00Z") ==
          datetime(2007, 1, 25, 12, 0, tzinfo=timezone.utc))

# Remember, exit status 0 (i.e. false) means success.
sys.exit(not status)
