#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    update-alternatives \
        --install /usr/bin/php-config php-config /usr/bin/php-config.default 100 \
        --slave /usr/share/man/man1/php-config.1.gz php-config.1.gz /usr/share/man/man1/php-config.default.1.gz
    update-alternatives \
        --install /usr/bin/phpize phpize /usr/bin/phpize.default 100 \
        --slave /usr/share/man/man1/phpize.1.gz phpize.1.gz /usr/share/man/man1/phpize.default.1.gz
fi

#DEBHELPER#

exit 0
