usr/include/postgresql/ecpg*.h
usr/include/postgresql/informix/*
usr/include/postgresql/pgtypes*.h
usr/include/postgresql/sql3types.h
usr/include/postgresql/sqlca.h
usr/include/postgresql/sqlda*.h
usr/lib/*/libecpg.a
usr/lib/*/libecpg.so
usr/lib/*/libecpg_compat.a
usr/lib/*/libecpg_compat.so
usr/lib/*/libpgtypes.a
usr/lib/*/libpgtypes.so
usr/lib/*/pkgconfig/libecpg.pc
usr/lib/*/pkgconfig/libecpg_compat.pc
usr/lib/*/pkgconfig/libpgtypes.pc
usr/lib/postgresql/*/bin/ecpg usr/bin
usr/share/locale/*/*/ecpg-*.mo
usr/share/postgresql/*/man/man1/ecpg.1* /usr/share/man/man1
