usr/include/postgresql/internal/*
usr/include/postgresql/libpq-events.h
usr/include/postgresql/libpq-fe.h
usr/include/postgresql/libpq/libpq-fs.h
usr/include/postgresql/pg_config*.h
usr/include/postgresql/postgres_ext.h
usr/lib/*/libpq.a
usr/lib/*/libpq.so
usr/lib/*/pkgconfig/libpq.pc
# pg_config manpage for both the perl and C versions
usr/share/postgresql/*/man/man1/pg_config.1* /usr/share/man/man1
