#!/bin/sh
set -efu

pythons="$(py3versions -s)"
cp -a c testing "$AUTOPKGTEST_TMP"

# Not appropriate:
rm "$AUTOPKGTEST_TMP"/testing/cffi0/test_version.py
rm "$AUTOPKGTEST_TMP"/testing/cffi1/test_parse_c_type.py

# Temporary hack until cffi defaults to calling virtualenv with --never-download
export VIRTUALENV_DOWNLOAD=no

# Delete any stale __pycache__s
find "$AUTOPKGTEST_TMP" -name '__pycache__' -print0 | xargs -0 rm -rf

cd "$AUTOPKGTEST_TMP"
for py in $pythons; do
	echo "======= $py ======="
	$py -m pytest --tb=native c testing
	echo "======= $py-dbg ======="
	$py-dbg -m pytest --tb=native c testing 2>&1
done
