usr/share/aclocal/cmake.m4
usr/share/cmake-*/
usr/share/emacs/site-lisp/cmake-mode.el
# usr/share/man/man7/cmake-buildsystem.7
# usr/share/man/man7/cmake-commands.7
# usr/share/man/man7/cmake-compile-features.7
# usr/share/man/man7/cmake-developer.7
# usr/share/man/man7/cmake-env-variables.7
# usr/share/man/man7/cmake-file-api.7
# usr/share/man/man7/cmake-generator-expressions.7
# usr/share/man/man7/cmake-generators.7
# usr/share/man/man7/cmake-language.7
# usr/share/man/man7/cmake-modules.7
# usr/share/man/man7/cmake-packages.7
# usr/share/man/man7/cmake-policies.7
# usr/share/man/man7/cmake-properties.7
# usr/share/man/man7/cmake-qt.7
# usr/share/man/man7/cmake-server.7
# usr/share/man/man7/cmake-toolchains.7
# usr/share/man/man7/cmake-variables.7
# usr/share/man/man7/cpack-generators.7
usr/share/vim/vimfiles/indent/cmake.vim
usr/share/vim/vimfiles/syntax/cmake.vim
