#!/bin/sh

cat > setup.py <<EOF
from setuptools import setup, find_packages

setup(
    name='stupid',
    version='0.0',
    packages=find_packages(),
    )
EOF

cat > stupid.py <<EOF
print('stupid module')
EOF

virtualenv -p python3 $ADTTMP/p3
. $ADTTMP/p3/bin/activate
python setup.py install
python -c "import stupid"
