#!/bin/sh
set -e
# Enter testing directory so that we don't accidentally find 'py' directory but
# instead use the system py module.
cd testing

PYVERS=$(pyversions -vi)
for py in $PYVERS ; do
  find -name "*.pyc" -delete
  TMPDIR="$ADDTMP" LANG=C.UTF-8 python$py -m pytest .
done
